# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 23:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allele',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=5)),
                ('wild_type', models.BooleanField(default=False)),
                ('dominance', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=5)),
                ('sex_linked', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='allele',
            name='gene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genes.Gene'),
        ),
    ]
